### ISSUE TITLE
results don't match the results in article

### ISSUE THREAD

**Issue by pavlexander** [VXU1230/Medium-Tutorials#3]
Hi,

I have executed the code that you have created (as is, without modifications) on my machine and the results are very poor.

With maximum smoothing:

![image](https://user-images.githubusercontent.com/20644772/103457620-81a43980-4d09-11eb-9eb2-1f7f4ac7b157.png)

Without smoothing:

![image](https://user-images.githubusercontent.com/20644772/103457626-8ec12880-4d09-11eb-9258-f524ef3c44c3.png)

**I see that in some cases the maximum reward had reached the targeted 200 points, however, the result is much more diverse and random when compared to the images that you have provided:**

![image](https://user-images.githubusercontent.com/20644772/103457650-b31d0500-4d09-11eb-9841-205e3776ea64.png)

Could you please elaborate - what am I doing wrong? Have you by any chance changed the hyperparameters in the source code after the article was written?

Thank you for your hard work!

**Comment by VXU1230** [comment]
Thanks for reaching out!
It is worth mentioning that CartPole is a very difficult environment for DQN algorithm to learn in general. In fact, the learning often fails and the result shown above was achieved after many iterations of the code.

To improve the performance and reduce learning time, I encourage you to explore more model structures (more layers, convolutional layers, other activation functions etc.) and hyper parameter settings (target net copy step, experience size, epsilon decay values etc.).
[rl-baselines-zoo](https://github.com/araffin/rl-baselines-zoo/blob/master/hyperparams/dqn.yml) has provided hyperparameters you can refer to. :)
